// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const TOGGLE_LOADING_ON = 'TOGGLE_LOADING_ON'
export const TOGGLE_LOADING_OFF = 'TOGGLE_LOADING_OFF'


